CREATE TABLESPACE TS_GKV
DATAFILE 'C:\Labs\Databases\Lab2\TS_GKV1.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;


CREATE TEMPORARY TABLESPACE TS_GKV_TEMP
TEMPFILE 'C:\Labs\Databases\Lab2\TS_GKV_TEMP1.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M;

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;

alter session set "_ORACLE_SCRIPT" = true;

CREATE ROLE RL_GKVCORE;
GRANT CREATE SESSION, CREATE TABLE, DROP ANY TABLE,
    CREATE VIEW, DROP ANY VIEW,
    CREATE PROCEDURE, DROP ANY PROCEDURE TO RL_GKVCORE;
COMMIT;

SELECT * FROM DBA_ROLES WHERE ROLE = 'RL_GKVCORE';
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'RL_GKVCORE';

CREATE PROFILE PF_GKVCORE LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_GKVCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE USER GKVCORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_GKV
TEMPORARY TABLESPACE TS_GKV_TEMP
PROFILE PF_GKVCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_GKVCORE TO GKVCORE;

CREATE TABLESPACE GKV_QDATA
DATAFILE 'C:\Labs\Databases\Lab2\GKV_QDATA.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M
MAXSIZE 20M
OFFLINE;

ALTER TABLESPACE GKV_QDATA ONLINE;

ALTER USER GKVCORE QUOTA 2M ON GKV_QDATA;

INSERT INTO GKVCORE.PRODUCTS (NAMEOFPRODUCT, PRICE, AMOUNT) VALUES ('Молоко', 2, 10);
INSERT INTO GKVCORE.PRODUCTS (NAMEOFPRODUCT, PRICE, AMOUNT) VALUES ('Хлеб', 1, 25);
INSERT INTO GKVCORE.PRODUCTS (NAMEOFPRODUCT, PRICE, AMOUNT) VALUES ('Мороженое', 2.5, 5);
COMMIT;